//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFacturacionDesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULOS
    {
        public ARTICULOS()
        {
            this.DETALLE_FACTURA = new HashSet<DETALLE_FACTURA>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public int idCategoria { get; set; }
        public double costoUnitario { get; set; }
        public double precioUnitario { get; set; }
        public int stock { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<DETALLE_FACTURA> DETALLE_FACTURA { get; set; }
        public virtual CATEGORIA CATEGORIA { get; set; }
    }
}
