//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFacturacionDesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        public CLIENTES()
        {
            this.FACTURAS = new HashSet<FACTURAS>();
        }
    
        public int id { get; set; }
        public string nombreComercial { get; set; }
        public string razonSocial { get; set; }
        public string RNC_CED { get; set; }
        public string cuentaContable { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<FACTURAS> FACTURAS { get; set; }
    }
}
