//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFacturacionDesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDICIONESPAGO
    {
        public CONDICIONESPAGO()
        {
            this.FACTURAS = new HashSet<FACTURAS>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public int cantidadDias { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<FACTURAS> FACTURAS { get; set; }
    }
}
