//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFacturacionDesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FACTURA
    {
        public int idFactura { get; set; }
        public int idArticulo { get; set; }
        public int cantidad { get; set; }
        public double precioUnitario { get; set; }
    
        public virtual ARTICULOS ARTICULOS { get; set; }
        public virtual FACTURAS FACTURAS { get; set; }
    }
}
