//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFacturacionDesk
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesFACTURACION : DbContext
    {
        public EntitiesFACTURACION()
            : base("name=EntitiesFACTURACION")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ARTICULOS> ARTICULOS { get; set; }
        public DbSet<CATEGORIA> CATEGORIA { get; set; }
        public DbSet<CLIENTES> CLIENTES { get; set; }
        public DbSet<CONDICIONESPAGO> CONDICIONESPAGO { get; set; }
        public DbSet<DETALLE_FACTURA> DETALLE_FACTURA { get; set; }
        public DbSet<FACTURAS> FACTURAS { get; set; }
        public DbSet<VENDEDORES> VENDEDORES { get; set; }
    }
}
